uploads = []
outputs = []

[[generated]]
id = "LrRioAY47QdMVHbAzD6R9"
uri = "file://artifacts/farah/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ElxWXEt_UGSx2AN1TSxPA"
uri = "file://artifacts/farah/assets/images/hero-hall.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7AeXuKgozIAzI7h3GyyMi"
uri = "file://artifacts/farah/assets/images/cat-music.png"
type = "image"
title = "generated_image"

[[generated]]
id = "w7vavI-GGWfLwPVlOUXXT"
uri = "file://artifacts/farah/assets/images/cat-food.png"
type = "image"
title = "generated_image"

[[generated]]
id = "aRpc4KBWQMD_pdIW9K1id"
uri = "file://artifacts/farah/assets/images/cat-photo.png"
type = "image"
title = "generated_image"

[[generated]]
id = "eHK8jaqnfF5kBy7CkHGIo"
uri = "file://artifacts/farah/assets/images/cat-flowers.png"
type = "image"
title = "generated_image"
