// Static assets shared between screens. Real provider/service data lives in
// Supabase — see lib/data.ts and contexts/AppContext.tsx.

// Comprehensive list of Saudi cities (major + secondary). Stored as
// Arabic names — the canonical key everywhere in the app. EN labels
// live in CITY_NAME_EN below.
export const CITIES = [
  // Top-tier
  "الرياض",
  "جدة",
  "مكة المكرمة",
  "المدينة المنورة",
  "الدمام",
  "الخبر",
  "الظهران",
  "الطائف",
  "تبوك",
  "أبها",
  "بريدة",
  "حائل",
  "نجران",
  "جازان",
  "ينبع",
  "الجبيل",
  "الأحساء",
  "الهفوف",
  "خميس مشيط",
  "عرعر",
  "سكاكا",
  "القطيف",
  "الباحة",
  "القصيم",
  "عنيزة",
  "الرس",
  "حفر الباطن",
  "الخرج",
  "المجمعة",
  "الزلفي",
  "شقراء",
  "الدوادمي",
  "وادي الدواسر",
  "بيشة",
  "محايل عسير",
  "تنومة",
  "النماص",
  "ضباء",
  "أملج",
  "العلا",
  "بدر",
  "رابغ",
  "خيبر",
  "تيماء",
  "الوجه",
  "رفحاء",
  "طريف",
  "القريات",
  "صبيا",
  "أبو عريش",
  "صامطة",
];

// AR ↔ EN mapping for the canonical city names. Cities in the DB are
// always stored as the Arabic string (CITIES[]) — this map only flips
// the UI label for display. Keep keys identical to CITIES entries.
export const CITY_NAME_EN: Record<string, string> = {
  "الرياض": "Riyadh",
  "جدة": "Jeddah",
  "مكة المكرمة": "Makkah",
  "المدينة المنورة": "Madinah",
  "الدمام": "Dammam",
  "الخبر": "Khobar",
  "الظهران": "Dhahran",
  "الطائف": "Taif",
  "تبوك": "Tabuk",
  "أبها": "Abha",
  "بريدة": "Buraydah",
  "حائل": "Hail",
  "نجران": "Najran",
  "جازان": "Jazan",
  "ينبع": "Yanbu",
  "الجبيل": "Jubail",
  "الأحساء": "Al-Ahsa",
  "الهفوف": "Hofuf",
  "خميس مشيط": "Khamis Mushait",
  "عرعر": "Arar",
  "سكاكا": "Sakaka",
  "القطيف": "Qatif",
  "الباحة": "Al-Baha",
  "القصيم": "Qassim",
  "عنيزة": "Unayzah",
  "الرس": "Ar Rass",
  "حفر الباطن": "Hafar Al-Batin",
  "الخرج": "Al-Kharj",
  "المجمعة": "Al-Majma'ah",
  "الزلفي": "Az Zulfi",
  "شقراء": "Shaqra",
  "الدوادمي": "Ad Dawadmi",
  "وادي الدواسر": "Wadi Ad-Dawasir",
  "بيشة": "Bisha",
  "محايل عسير": "Muhayil Asir",
  "تنومة": "Tanomah",
  "النماص": "An Namas",
  "ضباء": "Duba",
  "أملج": "Umluj",
  "العلا": "AlUla",
  "بدر": "Badr",
  "رابغ": "Rabigh",
  "خيبر": "Khaybar",
  "تيماء": "Tayma",
  "الوجه": "Al Wajh",
  "رفحاء": "Rafha",
  "طريف": "Turaif",
  "القريات": "Al Qurayyat",
  "صبيا": "Sabya",
  "أبو عريش": "Abu Arish",
  "صامطة": "Samtah",
};

/** Localized display label for a city stored as its Arabic name. */
export function localizedCityName(arName: string, lang: string): string {
  if (lang === "en") return CITY_NAME_EN[arName] ?? arName;
  return arName;
}

const COVER = {
  halls: require("../assets/images/hero-hall.png"),
  music: require("../assets/images/cat-music.png"),
  food: require("../assets/images/cat-food.png"),
  photo: require("../assets/images/cat-photo.png"),
  flowers: require("../assets/images/cat-flowers.png"),
};

// Fallback cover image for a provider, keyed by category slug.
export const COVER_BY_CATEGORY: Record<string, number> = {
  halls: COVER.halls,
  munshideen: COVER.music,
  poets: COVER.music,
  "ardha-poets": COVER.music,
  "dama-shilat": COVER.music,
  drums: COVER.music,
  audio: COVER.music,
  qahwaji: COVER.food,
  restaurants: COVER.food,
  cafes: COVER.food,
  "popular-food": COVER.food,
  sweets: COVER.food,
  photo: COVER.photo,
  video: COVER.photo,
  "female-photo": COVER.photo,
  flowers: COVER.flowers,
  "wedding-prep": COVER.flowers,
  furniture: COVER.flowers,
  "women-section": COVER.flowers,
  organizers: COVER.halls,
};

export const DEFAULT_COVER = COVER.halls;
