export const STRINGS = {
  appName: "فرح",
  tagline: "كل ما تحتاجه لمناسبتك في مكان واحد",

  // Auth
  welcome: "أهلاً بك في فرح",
  loginTitle: "تسجيل الدخول",
  phoneLabel: "رقم الجوال",
  phonePlaceholder: "5XXXXXXXX",
  sendOtp: "إرسال رمز التحقق",
  otpTitle: "رمز التحقق",
  otpDesc: "أدخل الرمز المرسل إلى رقمك",
  otpHint: "للتجربة استخدم: 1234",
  verify: "تأكيد الدخول",
  resend: "إعادة إرسال الرمز",
  changeNumber: "تغيير الرقم",

  // Tabs
  home: "الرئيسية",
  bookings: "حجوزاتي",
  notifications: "الإشعارات",
  profile: "حسابي",

  // Home
  greeting: "مرحباً",
  searchPlaceholder: "ابحث عن خدمة أو مزود...",
  featured: "الأكثر طلباً",
  allCategories: "كل التصنيفات",
  topRated: "الأعلى تقييماً",
  exploreCategory: "تصفح",

  // Provider
  about: "نبذة",
  servicesAndPrices: "الخدمات والأسعار",
  reviewsTitle: "التقييمات",
  bookNow: "احجز الآن",
  contactProvider: "اتصال",
  galleryTitle: "معرض الأعمال",
  startingFrom: "يبدأ من",
  sar: "ر.س",
  perBooking: "للحجز",

  // Booking
  newBooking: "حجز جديد",
  selectService: "اختر الخدمة",
  selectDate: "تاريخ المناسبة",
  selectTime: "الوقت",
  location: "الموقع",
  locationPlaceholder: "حي / مدينة / عنوان تفصيلي",
  notes: "ملاحظات إضافية",
  notesPlaceholder: "أي تفاصيل تساعد مزود الخدمة...",
  submitBooking: "تأكيد الحجز",
  bookingPlaced: "تم إرسال الحجز",
  bookingPlacedDesc: "سيتم التواصل معك من قبل مزود الخدمة قريباً",

  // Statuses
  statusPending: "قيد المراجعة",
  statusAccepted: "مقبول",
  statusRejected: "مرفوض",
  statusCompleted: "مكتمل",
  statusCancelled: "ملغي",

  // Bookings
  myBookings: "حجوزاتي",
  noBookings: "لا توجد حجوزات بعد",
  noBookingsDesc: "استكشف الخدمات وابدأ بحجز مناسبتك المثالية",
  exploreNow: "استكشف الآن",
  rate: "أضف تقييم",
  cancel: "إلغاء",
  rateService: "قيّم الخدمة",
  ratePrompt: "كيف كانت تجربتك؟",
  rateHint: "ساعد الآخرين بمشاركة رأيك",
  comment: "تعليقك",
  commentPlaceholder: "اكتب تعليقاً للخدمة...",
  submitReview: "إرسال التقييم",
  thanksReview: "شكراً لمشاركة رأيك",

  // Notifications
  noNotifications: "لا توجد إشعارات",
  noNotificationsDesc: "ستصلك إشعارات الحجوزات والتحديثات هنا",

  // Profile
  customerAccount: "حساب عميل",
  providerAccount: "حساب مزود خدمة",
  adminAccount: "حساب المالك",
  switchToProvider: "الانتقال لواجهة مزود الخدمة",
  switchToAdmin: "لوحة تحكم المالك",
  switchToCustomer: "العودة لواجهة العميل",
  myAccount: "بياناتي",
  language: "اللغة",
  arabic: "العربية",
  support: "الدعم الفني",
  aboutApp: "حول التطبيق",
  logout: "تسجيل الخروج",
  enableTesterMode: "وضع التجربة",
  enableTesterModeDesc: "تجربة جميع الواجهات (مالك ومزود)",

  // Provider zone
  providerHome: "لوحة مزود الخدمة",
  providerStats: "إحصائيات سريعة",
  totalBookings: "إجمالي الحجوزات",
  pendingBookings: "بانتظار الرد",
  completedBookings: "مكتملة",
  earnings: "الأرباح",
  commissionFee: "بعد خصم العمولة",
  myServices: "خدماتي",
  addService: "إضافة خدمة",
  editService: "تعديل خدمة",
  serviceTitle: "اسم الخدمة",
  servicePrice: "السعر (ر.س)",
  serviceDuration: "المدة",
  saveService: "حفظ",
  deleteService: "حذف",
  incomingRequests: "طلبات الحجز",
  acceptRequest: "قبول",
  rejectRequest: "رفض",
  markCompleted: "وضع كمكتمل",
  earningsBreakdown: "تفاصيل الأرباح",

  // Admin
  adminHome: "لوحة تحكم المالك",
  manageUsers: "إدارة المستخدمين",
  manageProviders: "إدارة مقدمي الخدمة",
  manageCategories: "إدارة التصنيفات",
  manageBookings: "إدارة الطلبات",
  commissions: "العمولات",
  reports: "التقارير والإحصائيات",
  broadcastNotification: "إشعار جماعي",
  commissionLabel: "نسبة العمولة (%)",
  saveSettings: "حفظ التغييرات",
  saved: "تم الحفظ بنجاح",
  totalRevenue: "إجمالي الأرباح",
  totalUsers: "إجمالي المستخدمين",
  activeProviders: "مزودي الخدمة النشطين",
  topCategories: "أكثر الفئات طلباً",
  addCategory: "إضافة تصنيف",
  newCategoryName: "اسم التصنيف الجديد",
  add: "إضافة",
  delete: "حذف",
  broadcastTitle: "عنوان الإشعار",
  broadcastBody: "محتوى الإشعار",
  send: "إرسال",
  sentToAll: "تم إرسال الإشعار لجميع المستخدمين",

  // Common
  back: "رجوع",
  next: "التالي",
  done: "تم",
  yes: "نعم",
  no: "لا",
  confirm: "تأكيد",
  loading: "جاري التحميل...",
  retry: "إعادة المحاولة",
  empty: "لا توجد بيانات",
  search: "بحث",
  in: "في",
  by: "بواسطة",
  from: "من",
  to: "إلى",
};

export const STATUS_LABELS: Record<string, string> = {
  pending: STRINGS.statusPending,
  accepted: STRINGS.statusAccepted,
  rejected: STRINGS.statusRejected,
  completed: STRINGS.statusCompleted,
  cancelled: STRINGS.statusCancelled,
};
