export const STRINGS = {
  appName: "فرح",
  tagline: "كل ما تحتاجه لمناسبتك في مكان واحد",

  // Auth
  welcome: "أهلاً بك في فرح",
  loginTitle: "تسجيل الدخول",
  signupTitle: "إنشاء حساب جديد",
  emailLabel: "البريد الإلكتروني",
  emailPlaceholder: "example@email.com",
  passwordLabel: "كلمة المرور",
  passwordPlaceholder: "٨ أحرف على الأقل",
  confirmPasswordLabel: "تأكيد كلمة المرور",
  loginAction: "دخول",
  signupAction: "إنشاء الحساب",
  haveAccount: "لديك حساب بالفعل؟",
  noAccount: "ليس لديك حساب؟",
  goToLogin: "تسجيل الدخول",
  goToSignup: "أنشئ حساباً",
  browseAsGuest: "تصفّح كزائر",
  invalidEmail: "البريد الإلكتروني غير صحيح",
  invalidPassword: "كلمة المرور يجب أن تكون ٨ أحرف على الأقل",
  passwordsMismatch: "كلمتا المرور غير متطابقتين",
  loginFailed: "فشل تسجيل الدخول. تحقق من البريد وكلمة المرور.",
  signupFailed: "تعذّر إنشاء الحساب",
  emailNotConfirmed: "بريدك الإلكتروني غير مفعّل. تحقق من بريدك أو أعد إرسال الرمز.",
  otpTitle: "رمز التحقق",
  otpEmailDesc: "أدخل الرمز المكوّن من ٦ أرقام المرسل إلى بريدك",
  otpInvalid: "رمز غير صحيح، حاول مرة أخرى",
  otpSendFailed: "تعذّر إرسال الرمز، حاول مجدداً",
  verify: "تأكيد",
  resend: "إعادة إرسال الرمز",

  // Profile setup (إكمال البيانات)
  profileSetupTitle: "أكمل بياناتك",
  profileSetupDesc: "نحتاج بعض المعلومات قبل البدء",
  fullNameLabel: "الاسم الكامل",
  phoneLabel: "رقم الجوال",
  phonePlaceholder: "5XXXXXXXX",
  avatarLabel: "الصورة الشخصية / الشعار",
  pickImage: "اختر صورة",
  changeImage: "تغيير الصورة",
  genderLabel: "الجنس",
  genderMale: "ذكر",
  genderFemale: "أنثى",
  ageLabel: "العمر",
  agePlaceholder: "العمر بالسنوات",
  preferredLanguageLabel: "اللغة المفضلة",
  saveAndContinue: "حفظ ومتابعة",
  profileSaveFailed: "تعذّر حفظ البيانات، حاول مرة أخرى",
  fillAllRequired: "الرجاء إكمال جميع الحقول المطلوبة",
  invalidPhone: "رقم الجوال غير صحيح",
  invalidAge: "العمر غير صحيح",
  uploadingImage: "جاري رفع الصورة...",

  // Tabs
  home: "الرئيسية",
  bookings: "حجوزاتي",
  notifications: "الإشعارات",
  profile: "حسابي",

  // Home
  greeting: "مرحباً",
  searchPlaceholder: "ابحث عن خدمة أو مزود...",
  featured: "الأكثر طلباً",
  allCategories: "كل التصنيفات",
  topRated: "الأعلى تقييماً",
  exploreCategory: "تصفح",

  // Provider
  about: "نبذة",
  servicesAndPrices: "الخدمات والأسعار",
  reviewsTitle: "التقييمات",
  bookNow: "احجز الآن",
  contactProvider: "اتصال",
  galleryTitle: "معرض الأعمال",
  startingFrom: "يبدأ من",
  sar: "ر.س",
  perBooking: "للحجز",

  // Booking
  newBooking: "حجز جديد",
  selectService: "اختر الخدمة",
  selectDate: "تاريخ المناسبة",
  selectTime: "الوقت",
  location: "موقع المناسبة",
  locationPlaceholder: "https://maps.app.goo.gl/...",
  locationHint: "أرفق رابط قوقل ماب لمكان المناسبة لتسهيل وصول مزود الخدمة",
  useCurrentLocation: "استخدام موقعي الحالي",
  openInMaps: "فتح في الخرائط",
  locationRequired: "الرجاء إرفاق رابط قوقل ماب أو استخدام موقعك الحالي",
  cityLabel: "المدينة",
  fetchingLocation: "جاري تحديد موقعك...",
  locationDenied: "تم رفض الإذن لاستخدام الموقع",
  notes: "ملاحظات إضافية",
  notesPlaceholder: "أي تفاصيل تساعد مزود الخدمة...",
  submitBooking: "تأكيد الحجز",
  bookingPlaced: "تم إرسال الحجز",
  bookingPlacedDesc: "سيتم التواصل معك من قبل مزود الخدمة قريباً",

  // Statuses
  statusPending: "قيد المراجعة",
  statusAccepted: "مقبول",
  statusRejected: "مرفوض",
  statusCompleted: "مكتمل",
  statusCancelled: "ملغي",

  // Bookings
  myBookings: "حجوزاتي",
  noBookings: "لا توجد حجوزات بعد",
  noBookingsDesc: "استكشف الخدمات وابدأ بحجز مناسبتك المثالية",
  exploreNow: "استكشف الآن",
  rate: "أضف تقييم",
  cancel: "إلغاء",
  rateService: "قيّم الخدمة",
  ratePrompt: "كيف كانت تجربتك؟",
  rateHint: "ساعد الآخرين بمشاركة رأيك",
  comment: "تعليقك",
  commentPlaceholder: "اكتب تعليقاً للخدمة...",
  submitReview: "إرسال التقييم",
  thanksReview: "شكراً لمشاركة رأيك",

  // Notifications
  noNotifications: "لا توجد إشعارات",
  noNotificationsDesc: "ستصلك إشعارات الحجوزات والتحديثات هنا",

  // Profile
  customerAccount: "حساب عميل",
  providerAccount: "حساب مزود خدمة",
  adminAccount: "حساب المالك",
  switchToProvider: "الانتقال لواجهة مزود الخدمة",
  switchToAdmin: "لوحة تحكم المالك",
  switchToCustomer: "العودة لواجهة العميل",
  myAccount: "بياناتي",
  language: "اللغة",
  arabic: "العربية",
  support: "الدعم الفني",
  aboutApp: "حول التطبيق",
  logout: "تسجيل الخروج",
  enableTesterMode: "وضع التجربة",
  enableTesterModeDesc: "تجربة جميع الواجهات (مالك ومزود)",

  // Provider zone
  providerHome: "لوحة مزود الخدمة",
  providerStats: "إحصائيات سريعة",
  totalBookings: "إجمالي الحجوزات",
  pendingBookings: "بانتظار الرد",
  completedBookings: "مكتملة",
  earnings: "الأرباح",
  commissionFee: "بعد خصم العمولة",
  myServices: "خدماتي",
  addService: "إضافة خدمة",
  editService: "تعديل خدمة",
  serviceTitle: "اسم الخدمة",
  servicePrice: "السعر (ر.س)",
  serviceDuration: "المدة",
  saveService: "حفظ",
  deleteService: "حذف",
  incomingRequests: "طلبات الحجز",
  acceptRequest: "قبول",
  rejectRequest: "رفض",
  markCompleted: "وضع كمكتمل",
  earningsBreakdown: "تفاصيل الأرباح",

  // Admin
  adminHome: "لوحة تحكم المالك",
  manageUsers: "إدارة المستخدمين",
  manageProviders: "إدارة مقدمي الخدمة",
  manageCategories: "إدارة التصنيفات",
  manageBookings: "إدارة الطلبات",
  commissions: "العمولات",
  reports: "التقارير والإحصائيات",
  broadcastNotification: "إشعار جماعي",
  commissionLabel: "نسبة العمولة (%)",
  saveSettings: "حفظ التغييرات",
  saved: "تم الحفظ بنجاح",
  totalRevenue: "إجمالي الأرباح",
  totalUsers: "إجمالي المستخدمين",
  activeProviders: "مزودي الخدمة النشطين",
  topCategories: "أكثر الفئات طلباً",
  addCategory: "إضافة تصنيف",
  newCategoryName: "اسم التصنيف الجديد",
  add: "إضافة",
  delete: "حذف",
  broadcastTitle: "عنوان الإشعار",
  broadcastBody: "محتوى الإشعار",
  send: "إرسال",
  sentToAll: "تم إرسال الإشعار لجميع المستخدمين",

  // Common
  back: "رجوع",
  next: "التالي",
  done: "تم",
  yes: "نعم",
  no: "لا",
  confirm: "تأكيد",
  loading: "جاري التحميل...",
  retry: "إعادة المحاولة",
  empty: "لا توجد بيانات",
  search: "بحث",
  in: "في",
  by: "بواسطة",
  from: "من",
  to: "إلى",
};

export const STATUS_LABELS: Record<string, string> = {
  pending: STRINGS.statusPending,
  accepted: STRINGS.statusAccepted,
  rejected: STRINGS.statusRejected,
  completed: STRINGS.statusCompleted,
  cancelled: STRINGS.statusCancelled,
};
