-- ============================================================
-- migration_v34: SKIPPED — superseded by v35
--
-- The original v34 dropped deposit / final-payment / payout columns
-- and tables under the assumption the platform would never touch the
-- customer's money. After re-reading the brief I realised the model
-- you actually want is:
--
--   • Deposit (10%) → provider's Moyasar account directly.
--   • Final (90%)   → platform's Moyasar account, then automatic
--                     Moyasar Payout to the provider for
--                     (final - 10% of full price).
--
-- That keeps every cent the platform deserves under platform control
-- (no provider can stiff the platform), and still gets the bulk of
-- the money to the provider on a quick payout cycle.
--
-- Because you confirmed you NEVER ran v34 in Supabase, no rollback is
-- needed — the old columns and the provider_payouts table are still
-- present. v35 just wires the new automatic split on top of them.
--
-- v34 is left in the repo as a no-op so the file numbering stays
-- contiguous and old run-logs referencing it don't 404.
-- ============================================================

-- Intentionally empty.
select 1 where false;
